services:
  app:
    platform: linux/amd64 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Backend
      - "3001:3001"  # Frontend
      - "3002:3002"  # Admin
      - "3003:3003"  # Shared
    env_file:
      - ./packages/shared/.env
      - ./apps/backend/.env
      - ./apps/frontend/.env.local
    # depends_on:
      # - postgres
      # - redis

  # postgres:
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=sporton
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

# volumes:
  # postgres_data:
  # redis_data:
