name: Deploy to EC2

on:
  push:
    branches:
      - main  # أو الفرع اللي عليه نشر

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.51.198.254
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/app"
      - name: Create .env file on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 13.51.198.254
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/app/packages/shared
            echo "${{ secrets.SHARED_ENV_FILE }}" > ~/app/packages/shared/.env
            mkdir -p ~/app/apps/backend
            echo "${{ secrets.backend_ENV_FILE }}" > ~/app/apps/backend/.env
            mkdir -p ~/app/apps/frontend
            echo "${{ secrets.frontend_ENV_FILE }}" > ~/app/apps/frontend/.env.local
            mkdir -p ~/app/apps/admin
            echo "${{ secrets.admin_ENV_FILE }}" > ~/app/apps/admin/.env.local
      - name: Run app on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 13.51.198.254
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose down || true
            docker-compose up -d --build
